M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Fri 04 Apr 2025 03:59:21 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-04T15:59:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0378
%
G90
G05
T1
X1.53Y-0.6984
X1.53Y-0.7984
T2
X1.53Y-0.8984
T0
M30
