M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Sat 15 Mar 2025 12:22:18 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-15T00:22:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0378
%
G90
G05
T1
X7.5Y-3.8234
X7.5Y-3.9234
T2
X7.5Y-4.0234
T0
M30
